#!/usr/bin/env python3
"""Fetch the ORCID biography and write it to _data/orcid.yml for the site.

ORCID's /person endpoint carries the free-text biography shown on the public
ORCID page. This script mirrors it into the site's data directory so
index.md can render it, keeping the "About Me" text on jxzhao.com and the
ORCID record from drifting apart.

Only the public API is read; nothing is written back to ORCID (that would
need an OAuth member token). If the biography is set to private, or has never
been filled in, ORCID returns no content and this writes an empty value --
index.md falls back to its hand-written text in that case.

Like fetch_orcid.py, this exits non-zero WITHOUT touching the output file if
ORCID is unreachable, so a transient network failure can never blank the
site's biography.

Standalone usage:
    python3 fetch_orcid_profile.py
    python3 fetch_orcid_profile.py --dry-run
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from fetch_orcid import ORCID_ID, USER_AGENT, FetchError, _get_with_backoff

CV_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = CV_DIR.parent
OUTPUT_YML = REPO_ROOT / "_data" / "orcid.yml"

ORCID_PERSON_URL = f"https://pub.orcid.org/v3.0/{ORCID_ID}/person"


def fetch_biography() -> str:
    """Return the public ORCID biography, or '' if it is unset or private."""
    try:
        resp = _get_with_backoff(
            ORCID_PERSON_URL,
            {"Accept": "application/json", "User-Agent": USER_AGENT},
        )
    except FetchError as exc:
        raise FetchError(f"ORCID unreachable: {exc}") from exc

    try:
        data = resp.json()
    except ValueError as exc:
        raise FetchError(f"ORCID returned invalid JSON: {exc}") from exc

    biography = data.get("biography") or {}
    # `visibility` is "public" whenever the field is returned at all by the
    # public API, but check anyway so a future API change fails closed.
    if biography.get("visibility") not in (None, "public", "PUBLIC"):
        return ""
    return (biography.get("content") or "").strip()


def build(dry_run: bool) -> int:
    try:
        biography = fetch_biography()
    except FetchError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print(f"{OUTPUT_YML} left untouched.", file=sys.stderr)
        return 1

    if biography:
        print(f"ORCID: biography is {len(biography)} character(s).")
    else:
        print("ORCID: no public biography set; writing an empty value "
              "(index.md will use its hand-written text).")

    body = yaml.safe_dump(
        {"orcid": ORCID_ID, "biography": biography},
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=True,
        width=88,
    )
    out = (
        "# _data/orcid.yml -- GENERATED by cv/scripts/fetch_orcid_profile.py\n"
        "# Do not hand-edit. Source: the ORCID public API /person endpoint.\n"
        "# Edit the biography at https://orcid.org/my-orcid instead.\n\n"
        + body
    )

    previous = OUTPUT_YML.read_text(encoding="utf-8") if OUTPUT_YML.exists() else ""
    print("Biography unchanged." if out == previous else "Biography changed.")

    if dry_run:
        print("--dry-run: not writing _data/orcid.yml")
        return 0

    OUTPUT_YML.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = OUTPUT_YML.with_suffix(".yml.tmp")
    tmp_path.write_text(out, encoding="utf-8")
    tmp_path.replace(OUTPUT_YML)
    print(f"Wrote {OUTPUT_YML}.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would change, do not write the file")
    args = parser.parse_args()
    return build(dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
